In [1]:
import numpy as np

# Create two random 3x3 matrices
matrix1 = np.random.rand(3, 3)
matrix2 = np.random.rand(3, 3)

# Display the matrices
print("Matrix 1:")
print(matrix1)
print("\nMatrix 2:")
print(matrix2)

# Calculate the product of the two matrices using np.prod
product_result = np.prod([matrix1, matrix2])
print("\nProduct of matrices:")
print(product_result)

# Multiply the two matrices element-wise using np.multiply
multiply_result = np.multiply(matrix1, matrix2)
print("\nElement-wise multiplication of matrices:")
print(multiply_result)

# Calculate the dot product of the two matrices using np.dot
dot_product_result = np.dot(matrix1, matrix2)
print("\nDot product of matrices:")
print(dot_product_result)


Matrix 1:
[[0.44568815 0.15503715 0.16327064]
 [0.92304768 0.61555646 0.17115968]
 [0.31807244 0.12508686 0.47683011]]

Matrix 2:
[[0.36069141 0.28503121 0.52712123]
 [0.02909333 0.636701   0.77099188]
 [0.67360701 0.23528678 0.79637046]]

Product of matrices:
2.033324598521444e-09

Element-wise multiplication of matrices:
[[0.16075589 0.04419043 0.08606342]
 [0.02685454 0.39192541 0.13196273]
 [0.21425583 0.02943129 0.37973341]]

Dot product of matrices:
[[0.27524669 0.26416276 0.48448799]
 [0.46613832 0.69529442 1.09745357]
 [0.4395613  0.28249532 0.6438371 ]]


In [2]:
import numpy as np

# Create two NumPy arrays for demonstration
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])

# Union of arrays (Unique elements from both arrays)
union_result = np.union1d(array1, array2)
print("Union of arrays:", union_result)

# Intersection of arrays (Common elements in both arrays)
intersection_result = np.intersect1d(array1, array2)
print("Intersection of arrays:", intersection_result)

# Set difference (Elements in array1 but not in array2)
difference_result = np.setdiff1d(array1, array2)
print("Set difference (array1 - array2):", difference_result)

# XOR (Exclusive OR) of arrays
xor_result = np.setxor1d(array1, array2)
print("XOR of arrays:", xor_result)


Union of arrays: [1 2 3 4 5 6 7]
Intersection of arrays: [3 4 5]
Set difference (array1 - array2): [1 2]
XOR of arrays: [1 2 6 7]


In [6]:
import numpy as np

# Create a 1D array
array =np.array([2,3,4,5,6,7,8,6,10])

# Display the original array
print("Original Array:")
print(array)

# Cumulative Sum
cumulative_sum = np.cumsum(array)
print("\nCumulative Sum:")
print(cumulative_sum)

# Cumulative Product
cumulative_product = np.cumprod(array)
print("\nCumulative Product:")
print(cumulative_product)

# Discrete Difference (with n=3)
discrete_difference = np.diff(array, n=3)
print("\nDiscrete Difference (n=3):")
print(discrete_difference)

# Find Unique Elements
unique_elements = np.unique(array)
print("\nUnique Elements:")
print(unique_elements)


Original Array:
[ 2  3  4  5  6  7  8  6 10]

Cumulative Sum:
[ 2  5  9 14 20 27 35 41 51]

Cumulative Product:
[      2       6      24     120     720    5040   40320  241920 2419200]

Discrete Difference (n=3):
[ 0  0  0  0 -3  9]

Unique Elements:
[ 2  3  4  5  6  7  8 10]


In [7]:
import numpy as np

# Create two 1D arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([5, 4, 3, 2, 1])

# Perform addition using zip()
result_zip = np.array([a + b for a, b in zip(array1, array2)])
print("Addition using zip():")
print(result_zip)

# Perform addition using np.add()
result_np_add = np.add(array1, array2)
print("\nAddition using np.add():")
print(result_np_add)

# Define a user-defined addition function
def user_defined_add(a, b):
    return a + b

# Create a ufunc (user-defined function) from the user_defined_add function
add_ufunc = np.frompyfunc(user_defined_add, 2, 1)

# Perform addition using the user-defined function
result_user_defined = add_ufunc(array1, array2)
print("\nAddition using user-defined function (frompyfunc()):")
print(result_user_defined)


Addition using zip():
[6 6 6 6 6]

Addition using np.add():
[6 6 6 6 6]

Addition using user-defined function (frompyfunc()):
[6 6 6 6 6]


In [8]:
from functools import reduce
import numpy as np
from functools import reduce
from math import gcd

# Create an array of elements
array = np.array([12, 18, 24, 30])

# Function to find the LCM of two numbers
def lcm(a, b):
    return abs(a * b) // gcd(a, b)

# Function to find the GCD of an array of numbers
def find_gcd(arr):
    return reduce(gcd, arr)

# Function to find the LCM of an array of numbers
def find_lcm(arr):
    return reduce(lcm, arr)

# Find the GCD of the array
gcd_result = find_gcd(array)
print("GCD of the array:", gcd_result)

# Find the LCM of the array
lcm_result = find_lcm(array)
print("LCM of the array:", lcm_result)


GCD of the array: 6
LCM of the array: 360
